name: flutter_application_1
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  syncfusion_flutter_xlsio: ^20.4.54-beta
  excel: ^2.0.4
  crypto: any
  table_calendar: ^3.0.0
  flutter_local_notifications: ^9.5.3
  pdf: ^3.6.0
  open_file: ^3.0.1
  url_launcher: ^6.0.9
  file_picker: ^4.0.0
  flutter_email_sender: ^5.0.2
  http: ^0.13.3
  mailer: ^5.0.0
  connectivity_plus: ^2.3.5
  sqflite: any
  path_provider: any
  flutter_bloc: any 
  shared_preferences: ^2.0.6
  flutter_blurhash: ^0.6.0
  path: any


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/form_penilaian_alkes.xlsx
    - assets/form_penilaian_bangunan.xlsx
    - assets/form_penilaian_kendaraan.xlsx
    - assets/form_penilaian_pembiayaan.xlsx
    - assets/images/bgsplash.png
    - assets/images/logokemenkes.png
    - assets/images/logopuskesmas.png
    - assets/images/logors.jpg
    - assets/images/logodinkes.jpg
    - assets/images/puskesmasheader.jpeg
    - assets/images/profile_placeholder.png
